import {
  APPLICATION,
  CITIZEN_CARD,
  PAYSLIP,
  BANK_STATEMENT,
  LETTER_OF_GUARANTEE,
  CUSTOMER_SIGNATURE,
  VALID_CITIZEN_CARD,
  VALID_PAYSLIP,
  GUARANTOR_SIGNATURE,
  ADDRESS,
  AMOUNT_PRODUCT,
  AGE_INCOME_POSITION,
  COMPANY_NUMBER,
  AGE_INCOME_POSITION_APPROPRIATE,
  NAME_ACCOUNT_NUMBER,
  VALID_STATEMENT,
  VALID_BALANCE,
  IS_EXISTING_CUSTOMER,
  HAVE_OTHER_LOAN,
  TOTAL_ACCOUNT,
  CLOSED_ACCOUNT,
  OPEN_ACCOUNT,
  TOTAL_LOAN,
  TOTAL_MIN_PAY,
  HAVE_PAST_DUE_STATUS,
  INCOME_MORE_THAN_REQ,
  BALANCE_MORE_THAN_REQ,
  INCOME_MORE_THAN_DEBT,
} from 'texts'

export default {
  checkApplication: { label: APPLICATION, required: true },
  checkCitizenCard: { label: CITIZEN_CARD, required: true },
  checkPayslip: { label: PAYSLIP, required: true },
  checkBankStatement: { label: BANK_STATEMENT, required: true },
  checkLetterOfGuarantee: { label: LETTER_OF_GUARANTEE, required: true },
  checkAmountProduct: { label: AMOUNT_PRODUCT, required: true },
  checkAgeIncomePosition: { label: AGE_INCOME_POSITION, required: true },
  checkContactNumber: { label: COMPANY_NUMBER, required: true },
  checkAgeIncomePositionAppropriate: { label: AGE_INCOME_POSITION_APPROPRIATE, required: true },
  checkIsExistingCustomer: { label: IS_EXISTING_CUSTOMER, required: true },
  checkHaveOtherLoan: { label: HAVE_OTHER_LOAN, required: true },
  checkCustomerSignature: { label: CUSTOMER_SIGNATURE, required: true },
  checkValidCitizenCard: { label: VALID_CITIZEN_CARD, required: true },
  checkValidPayslip: { label: VALID_PAYSLIP, required: true },
  checkGuarantorSignature: { label: GUARANTOR_SIGNATURE, required: true },
  checkAddress: { label: ADDRESS, required: true },
  checkNameAccountNumber: { label: NAME_ACCOUNT_NUMBER, required: true },
  checkValidStatment: { label: VALID_STATEMENT, required: true },
  checkValidBalance: { label: VALID_BALANCE, required: true },
  checkIncomeMoreThanReq: { label: INCOME_MORE_THAN_REQ, required: true },
  checkBalanceMoreThanReq: { label: BALANCE_MORE_THAN_REQ, required: true },
  checkIncomeMoreThanDebt: { label: INCOME_MORE_THAN_DEBT, required: true },
  checkTotalAccount: { label: TOTAL_ACCOUNT, type: 'numeric', required: true },
  checkClosedAccount: { label: CLOSED_ACCOUNT, type: 'numeric', required: true },
  checkOpenAccount: { label: OPEN_ACCOUNT, type: 'numeric', required: true },
  checkTotalLoan: { label: TOTAL_LOAN, type: 'numeric', required: true },
  checkTotalMinPay: { label: TOTAL_MIN_PAY, type: 'numeric', required: true },
  checkFinancialStatus: { label: HAVE_PAST_DUE_STATUS, required: true },
}
