import { PropTypes } from 'react'
import {
  FILLFORM,
  WAIT_VERIFY,
  WAIT_ANALYST,
  WAIT_APPROVE,
} from 'appStatus'

const fillformData = {
  citizenId: '4101200009225',
  productId: '1001',
  loanTerm: '12',
  purpose: 'เพื่อซื้อสินค้าอุปโภค บริโภคอื่นๆ',
  appAmount: '30000',
  canPay: '100',
  createdDate: 'Sat Dec 10 2016 13:54:13 GMT+0700 (ICT)',
  lastModifiedDate: 'Sat Dec 10 2016 13:54:13 GMT+0700 (ICT)',
  status: 'fillform',
  title: 'นาย',
  firstname: 'อานุภาพ',
  lastname: 'วิรัตนภานุ',
  birthdate: '1983-07-13',
  currentAddressLine1: 'สุรวงศ์ซิตี้รีสอร์ท 99/71 ถนนนเรศ',
  currentSubDistrict: 'สี่พระยา',
  currentDistrict: 'บางรัก',
  currentProvince: 'กรุงเทพ',
  currentPostcode: '10500',
  currentTelNo: '-',
  currentMobileNo: '0866651662',
  permanentAddressLine1: '105/25 ถนนโพธิ์ร้าง',
  permanentSubDistrict: 'ในเมือง',
  permanentDistrict: 'เมือง',
  permanentProvince: 'สุรินทร์',
  permanentPostcode: '32000',
  permanentTelNo: '044515203',
  permanentMobileNo: '-',
  stayYear: '2',
  residentType: 'คอนโดมิเนี่ยม',
  stayMonth: '6',
  residentOwner: 'เป็นของตัวเอง',
  education: 'ปริญญาโท',
  maritalStatus: 'โสด',
  contactTitle: 'นาย',
  contactFirstname: 'ภาณุวัฒน์',
  contactLastname: 'วิรัตนภานุ',
  contactTelNo: '-',
  contactMobileNo: '+66866651662',
  relation: 'อื่นๆระบุ',
  otherRelation: 'บิดา',
  email: 'topscores@gmail.com',
  line: 'topscores',
  facebook: 'Arnupharp Viratanapanu',
  otherSocialMedia: 'twitter: topscores',
  employmentType: 'อื่นๆระบุ',
  otherEmploymentType: 'บริษัทตัวเอง',
  businessType: 'อื่นๆระบุ',
  otherBusinessType: 'ซอฟต์แวร์เฮาส์',
  occupation: 'โปรแกรมเมอร์',
  companyName: 'บริษัท ลานเกียร์ เทคโนโลยีจำกัด',
  officeAddressLine1: 'อาคารซอฟต์แวร์พาร์ค 99/23 ถนนแจ้งวัฒนะ',
  officeSubDistrict: 'คลองเกลือ',
  officeDistrict: 'ปากเกร็ด',
  officeProvince: 'นนทบุรี',
  officePostcode: '11120',
  officeTelNo: '-',
  officeMobileNo: '-',
  workYear: '4',
  workMonth: '6',
  income: '30000',
  extraIncome: '30000',
  extraIncomeSource: 'อื่นๆระบุ',
  otherExtraIncomeSource: 'ปันผล',
  documentAddress: 'ที่อยู่ปัจจุบัน',
  statementDate: '5',
  bank: 'ธนาคารกสิกรไทย',
  accountName: 'นายอานุภาพ วิรัตนภานุ',
  branchName: 'จามจุรีสแควร์',
  accountType: 'บัญชีออมทรัพย์',
  accountNo: '6302157438',
  knownFrom: 'อื่นๆระบุ',
  otherKnownFrom: 'หนังสือพิมพ์',
}
const verifyDocData = {
  checkApplication: 'มี',
  checkCitizenCard: 'มี',
  checkPayslip: 'มี',
  checkBankStatement: 'มี',
  checkLetterOfGuarantee: 'มี',
  checkAmountProduct: 'ถูก',
  checkAgeIncomePosition: 'ถูก',
  checkContactNumber: 'ถูก',
  checkAgeIncomePositionAppropriate: 'ถูก',
  checkIsExistingCustomer: 'ใช่',
  checkHaveOtherLoan: 'ใช่',
  checkCustomerSignature: 'ถูก',
  checkValidCitizenCard: 'ถูก',
  checkValidPayslip: 'ถูก',
  checkGuarantorSignature: 'ถูก',
  checkAddress: 'ถูก',
  checkNameAccountNumber: 'ถูก',
  checkValidStatment: 'ถูก',
  checkValidBalance: 'ถูก',
  checkIncomeMoreThanReq: 'ใช่',
  checkBalanceMoreThanReq: 'ใช่',
  checkIncomeMoreThanDebt: 'ใช่',
  checkTotalAccount: '3',
  checkClosedAccount: '2',
  checkOpenAccount: '1',
  checkTotalLoan: '20000',
  checkTotalMinPay: '1500',
  checkFinancialStatus: 'ปกติ',
}
const analystOpinionData = {
  analystOpinion: 'ผ่าน จ่ายดี จ่ายตรง เงินเดือนเยอะ',
  analystSuggestedAmount: '30000',
}
const approverOpinionData = {
  approverOpinion: 'เห็นด้วย',
  approverAmount: '30000',
}
const sampleData = {
  [FILLFORM]: {
    ...fillformData,
  },
  [WAIT_VERIFY]: {
    ...fillformData,
    ...verifyDocData,
  },
  [WAIT_ANALYST]: {
    ...fillformData,
    ...verifyDocData,
    ...analystOpinionData,
  },
  [WAIT_APPROVE]: {
    ...fillformData,
    ...verifyDocData,
    ...analystOpinionData,
    ...approverOpinionData,
  },
}

export const sampleDataByStatus = (status) => {
  const data = sampleData[status]
  // Sample data for application about to create which does not yet have status
  const newApplicationSampleData = {
    citizenId: '4101200009225',
    productId: '1001',
    loanTerm: '12',
    purpose: 'เพื่อซื้อสินค้าอุปโภค บริโภคอื่นๆ',
    appAmount: '30000',
    canPay: '100',
  }

  return data || newApplicationSampleData
}

const applicationShape = {
  id: PropTypes.string.isRequired,
  citizenId: PropTypes.string,
  productId: PropTypes.string,
  loanTerm: PropTypes.string,
  purpose: PropTypes.string,
  otherPurpose: PropTypes.string,
  appAmount: PropTypes.string,
  canPay: PropTypes.string,
  createdDate: PropTypes.string,
  lastModifiedDate: PropTypes.string,
  status: PropTypes.string,
  title: PropTypes.string,
  firstname: PropTypes.string,
  lastname: PropTypes.string,
  birthdate: PropTypes.string,
  currentAddressLine1: PropTypes.string,
  currentSubDistrict: PropTypes.string,
  currentDistrict: PropTypes.string,
  currentProvince: PropTypes.string,
  currentPostcode: PropTypes.string,
  currentTelNo: PropTypes.string,
  currentMobileNo: PropTypes.string,
  permanentAddressLine1: PropTypes.string,
  permanentSubDistrict: PropTypes.string,
  permanentDistrict: PropTypes.string,
  permanentProvince: PropTypes.string,
  permanentPostcode: PropTypes.string,
  permanentTelNo: PropTypes.string,
  permanentMobileNo: PropTypes.string,
  stayYear: PropTypes.string,
  residentType: PropTypes.string,
  stayMonth: PropTypes.string,
  residentOwner: PropTypes.string,
  education: PropTypes.string,
  maritalStatus: PropTypes.string,
  contactTitle: PropTypes.string,
  contactFirstname: PropTypes.string,
  contactLastname: PropTypes.string,
  contactTelNo: PropTypes.string,
  contactMobileNo: PropTypes.string,
  relation: PropTypes.string,
  otherRelation: PropTypes.string,
  email: PropTypes.string,
  line: PropTypes.string,
  facebook: PropTypes.string,
  otherSocialMedia: PropTypes.string,
  employmentType: PropTypes.string,
  otherEmploymentType: PropTypes.string,
  businessType: PropTypes.string,
  otherBusinessType: PropTypes.string,
  occupation: PropTypes.string,
  companyName: PropTypes.string,
  officeAddressLine1: PropTypes.string,
  officeSubDistrict: PropTypes.string,
  officeDistrict: PropTypes.string,
  officeProvince: PropTypes.string,
  officePostcode: PropTypes.string,
  officeTelNo: PropTypes.string,
  officeMobileNo: PropTypes.string,
  workYear: PropTypes.string,
  workMonth: PropTypes.string,
  income: PropTypes.string,
  extraIncome: PropTypes.string,
  extraIncomeSource: PropTypes.string,
  otherExtraIncomeSource: PropTypes.string,
  documentAddress: PropTypes.string,
  statementDate: PropTypes.string,
  bank: PropTypes.string,
  accountName: PropTypes.string,
  branchName: PropTypes.string,
  accountNo: PropTypes.string,
  knownFrom: PropTypes.string,
  otherKnownFrom: PropTypes.string,

  // VerifyDocument
  checkApplication: PropTypes.string,
  checkCitizenCard: PropTypes.string,
  checkPayslip: PropTypes.string,
  checkBankStatement: PropTypes.string,
  checkLetterOfGuarantee: PropTypes.string,
  checkAmountProduct: PropTypes.string,
  checkAgeIncomePosition: PropTypes.string,
  checkContactNumber: PropTypes.string,
  checkAgeIncomePositionAppropriate: PropTypes.string,
  checkIsExistingCustomer: PropTypes.string,
  checkHaveOtherLoan: PropTypes.string,
  checkCustomerSignature: PropTypes.string,
  checkValidCitizenCard: PropTypes.string,
  checkValidPayslip: PropTypes.string,
  checkGuarantorSignature: PropTypes.string,
  checkAddress: PropTypes.string,
  checkNameAccountNumber: PropTypes.string,
  checkValidStatment: PropTypes.string,
  checkValidBalance: PropTypes.string,
  checkIncomeMoreThanReq: PropTypes.string,
  checkBalanceMoreThanReq: PropTypes.string,
  checkIncomeMoreThanDebt: PropTypes.string,
  checkTotalAccount: PropTypes.string,
  checkClosedAccount: PropTypes.string,
  checkOpenAccount: PropTypes.string,
  checkTotalLoan: PropTypes.string,
  checkTotalMinPay: PropTypes.string,
  checkFinancialStatus: PropTypes.string,
}

export default applicationShape
