// Loan type
export const INSTALLMENT = 'Installment'
export const REVOLVING = 'Revolving'

// Purpose type
export const PERSONAL_LOAN = 'Personal Loan'
export const NANO_FINANCE = 'Nano Finance'

// Form label
export const CITIZEN_ID = 'เลขที่บัตรประจำตัวประชาชน'
export const CITIZEN_ID_PLACE_HOLDER = 'ไม่ต้องใส่ขีดหรือเว้นวรรค เช่น 4101200009225'
export const APPLYING_LOAN = 'สินเชื่อที่ต้องการสมัคร'
export const APPLYING_LOAN_NO_SELECT_TEXT = 'เลือกสินเชื่อที่ต้องการสมัคร'
export const LOAN_AMOUNT = 'วงเงินที่ต้องการ'
export const HOW_MUCH_YOU_CAN_PAY = 'กรุณาระบุจำนวนเงินที่สามารถผ่อนชำระได้'
export const PROCEED_TO_APPLICATION_FORM = 'กรอกใบสมัคร'
export const LOAN_PURPOSE = 'วัตถุประสงค์ในการขอสินเชื่อ'

// Personal Loan purpose
export const FOR_BUYING_GOODS = 'เพื่อซื้อสินค้าอุปโภค บริโภคอื่นๆ'

// Nano Finance purpose
export const FOR_NEW_BUSINESS = 'เพื่อเริ่มธุรกิจใหม่'
export const FOR_EXTENDING_EXISTING_BUSINESS = 'เพื่อขยายธุรกิจเดิม'

// Common purpose
export const OTHER = 'อื่นๆระบุ'

// Loan term
export const LOAN_TERM = 'ระยะเวลาผ่อนชำระ'
export const TWELVE_MONTHS = '12 เดือน'
export const TWENTY_FOUR_MONTHS = '24 เดือน'
export const THIRTY_SIX_MONTHS = '36 เดือน'
export const FOURTY_EIGHT_MONTHS = '48 เดือน'
export const MORE_THAN_SIXTY_MONTHS = '60 เดือน (ไม่ต่ำกว่า 500 บาทต่อเดือน)'

// Validators
export const PLEASE_SPECIFY = 'กรุณาระบุ'

// Application Form

// Submit button text
export const SAVE_DRAFT = 'บันทึก'
export const VERIFY_DATA = 'ตรวจสอบข้อมูล'
export const ANALYSE_LOAN = 'วิเคราะห์สินเชื่อ'
export const APPROVE_LOAN = 'อนุมัติสินเชื่อ'
export const APPROVE = 'อนุมัติ'

// Personal Info
export const APPLICATION_NO = 'เลขที่ใบสมัคร'
export const FULLNAME = 'ชื่อ - สกุล'
export const RESIDENT_INFO = 'ที่อยู่อาศัย'
export const STAY_PERIOD = 'อาศัยมานาน'
export const RESIDENT_TYPE = 'ประเภทที่อยู่อาศัย'
export const RESIDENT_OWNER = 'ประเภทการครอบครอง'
export const OWNER_ME = 'เป็นของตัวเอง'
export const OWNER_OTHER_PEOPLE = 'เป็นของผู้อื่น'
export const OWNER_RENT = 'เช่า'
export const OWNER_INSTALLMENT = 'ผ่อนชำระ'
export const OWNER_PARENT = 'อาศัยอยู่กับบิดา/มารดา'
export const EDUCATION = 'วุฒิการศึกษา'
export const HIGH_SCHOOL = 'ต่ำกว่ามัธยมปลาย/เทียบเท่า/ปวช.'
export const DIPLOMA = 'ปวส./ปวท./อนุปริญญา/เทียบเท่า'
export const BACHELOR = 'ปริญญาตรี'
export const MASTER = 'ปริญญาโท'
export const MARITAL_STATUS = 'สถานภาพ'
export const SINGLE = 'โสด'
export const MARRIED = 'สมรส'
export const DIVORCE = 'หย่า'
export const WIDOW = 'หม้าย'
export const SPOUSE_FULLNAME = 'ชื่อ - นามสกุล (คู่สมรส)'
export const SPOUSE_CONTACT = 'เบอร์ติดต่อ (คู่สมรส)'
export const CONTACT_PERSON = 'บุคคลที่อนุญาตให้ติดต่อได้'
export const RELATION = 'ความสัมพันธ์'
export const PARENTS = 'บิดา/มารดา'
export const HUSBAND = 'สามี'
export const WIFE = 'ภรรยา'
export const SOCIAL_MEDIA = 'ข้อมูลโซเชียลมีเดีย'
export const EMAIL = 'Email'
export const LINE = 'Line'
export const FACEBOOK = 'Facebook'

// Income Info
export const EMPLOYMENT_TYPE = 'ประเภทขององค์กร'
export const GOVERNMENT_OFFICER = 'ข้าราชการ'
export const STATE_ENTERPRISE = 'รัฐวิสาหกิจ'
export const COMPANY_EMPLOYEE = 'หน่วยงานเอกชน(ผู้สมัครเป็นพนักงาน)'
export const REGISTERED_COMPANY_OWNER = 'เจ้าของกิจการ(จดทะเบียนนิติบุคคล)'
export const UNREGISTERED_COMPANY_OWNER = 'เจ้าของกิจการ(ไม่จดทะเบียนนิติบุคคล)'
export const FREELANCE = 'รับจ้างทั่วไป/อาชีพอิสระ'
export const BUSINESS_TYPE = 'ประเภทธุรกิจ'
export const AGRICULTURE = 'ธุรกิจการเกษตร'
export const INDUSTRY = 'ธุรกิจอุตสาหกรรม'
export const COMMERCE = 'ธุรกิจพาณิชย์'
export const CONSTRUCTION = 'ธุรกิจก่อสร้าง'
export const FINANCE = 'ธุรกิจการเงิน'
export const SERVICE = 'ธุรกิจให้บริการ'
export const OCCUPATION = 'อาชีพ'
export const OCCUPATION_PLACEHOLDER = 'โปรดระบุให้ชัดเจน เช่น แพทย์, ทหาร'
export const COMPANY_NAME = 'ชื่อบริษัท/ที่ทำงาน'
export const COMPANY_NAME_PLACEHOLDER = 'เช่น บริษัท ไอทีทีพี จำกัด'
export const OFFICE_ADDRESS = 'ที่อยู่ที่ทำงาน'
export const POSITION = 'ตำแหน่ง'
export const EXPERIENCE = 'อายุงาน'
export const INCOME = 'รายได้'
export const REGULAR_INCOME = 'รายได้ประจำ/เดือน'
export const EXTRA_INCOME = 'รายได้พิเศษ/เดือน'
export const EXTRA_INCOME_SOURCE = 'แหล่งที่มาของรายได้อื่นๆ'
export const OT_BONUS = 'ค่าล่วงเวลา/โบนัส'

// LoanDetail
export const DOCUMENT_ADDRESS = 'ที่อยู่จัดส่งเอกสาร'
export const STATEMENT_DATE = 'วันที่ออก statement (สามารถชำระเงินหลังจากออก statement ภายใน 15 วัน)'
export const PAYTO = 'ช่องทางการรับเงินโอนเข้าบัญชีธนาคาร'
export const KTB = 'ธนาคารกรุงไทย'
export const BBL = 'ธนาคารกรุงเทพ'
export const SCB = 'ธนาคารไทยพาณิชย์'
export const KBANK = 'ธนาคารกสิกรไทย'
export const ACCOUNT_NAME = 'ชื่อบัญชี'
export const BRANCH_NAME = 'สาขา'
export const ACCOUNT_NO = 'เลขที่บัญชี'
export const ACCOUNT_TYPE = 'ประเภทบัญชี'
export const CURRENT = 'บัญชีประแสเงินสด'
export const SAVING = 'บัญชีออมทรัพย์'
export const KNOWN_FROM = 'ท่านรู้จักบริษัทจากสื่อใด'
export const CHOOSE_MEDIA = 'เลือกสื่อ'
export const BROCHURE = 'ใบปลิว'
export const BILLBOARD = 'ป้ายโฆษณา'
export const WEBSITE = 'เวบไซต์'
export const RADIO = 'วิทยุ'
export const TELEVISION = 'โทรทัศน์ ช่อง'
export const NEWSPAPER = 'หนังสือพิมพ์(ระบุ)'

// Application Form Tab
export const PERSONAL_INFO = 'ประวัติส่วนตัว'
export const INCOME_INFO = 'ข้อมูลรายได้'
export const LOAN_DETAIL = 'รายละเอียดการกู้'
export const VERIFY_DOCUMENT = 'ตรวจหลักฐาน'

// General
export const MONTH = 'เดือน'
export const YEAR = 'ปี'
export const FIRSTNAME = 'ชื่อ'
export const LASTNAME = 'นามสกุล'
export const TITLE = 'คำนำหน้า'
export const MR = 'นาย'
export const MRS = 'นาง'
export const MISS = 'นางสาว'
export const BAHT = 'บาท'
export const BIRTHDATE = 'วัน เดือน ปีเกิด'
export const SUB_DISTRICT = 'แขวง/ตำบล'
export const DISTRICT = 'เขต/อำเภอ'
export const PROVINCE = 'จังหวัด'
export const HOUSE = 'บ้าน'
export const TOWNHOUSE = 'ทาวน์เฮาส์'
export const CONDOMINIUM = 'คอนโดมิเนี่ยม'
export const TEL_NO = 'เบอร์โทรศัพท์'
export const MOBILE_NO = 'เบอร์มือถือ'
export const USE_SAMPLE_DATA = 'ใช้ข้อมูลตัวอย่าง'
export const TYPE = 'ประเภท'
export const CREATED_DATE = 'วันที่สร้าง'
export const LASTMODIFIED_DATE = 'แก้ไขล่าสุด'
export const NEW_APPLICATION = 'เพิ่มใบสมัคร'
export const ADDRESS = 'ที่อยู่'

// Address component
export const ADDRESS_LINE1 = 'บ้านเลขที่ หมู่บ้าน เลขที่ห้องพัก ตรอก ซอย ถนน'
export const POSTCODE = 'รหัสไปรษณีย์'
export const CURRENT_ADDRESS = 'ที่อยู่ปัจจุบัน'
export const PERMANENT_ADDRESS = 'ที่อยู่ตามทะเบียนบ้าน'
export const CONTACT_NUMBER = 'เบอร์ติดต่อ'

// Application status
export const ALL = 'ทั้งหมด'
export const FILLFORM = 'กรอกใบสมัคร'
export const WAIT_VERIFY = 'ตรวจหลักฐาน'
export const WAIT_ANALYST = 'วิเคราะห์สินเชื่อ'
export const WAIT_APPROVE = 'รออนุมัติ'

// Griddle
export const SHORT_APPLICATION_NO = 'เลขที่'
export const SHORT_CITIZEN_ID = 'บัตรประชาชน'
export const SHORT_LOAN_AMOUNT = 'วงเงิน'
export const STATUS = 'สถานะ'

// CHECKLIST
export const HAVE = 'มี'
export const DONT_HAVE = 'ไม่มี'
export const NOT_REQ = 'ไม่ต้อง'
export const CORRECT = 'ถูก'
export const INCORRECT = 'ไม่ถูก'
export const YES = 'ใช่'
export const NO = 'ไม่ใช่'
export const DOCUMENT = 'เอกสาร'
export const APPLICATION = 'ใบสมัคร'
export const CITIZEN_CARD = 'บัตรประชาชน'
export const PAYSLIP = 'สลิปเงินเดือน'
export const BANK_STATEMENT = 'สำเนาสมุดธนาคาร(ย้อนหลัง 3 เดือน)'
export const LETTER_OF_GUARANTEE = 'หนังสือค้ำประกัน'

export const DOCUMENT_VERIFICATION_RESULT = 'ผลการตรวจเอกสาร'
export const CUSTOMER_SIGNATURE = 'ลายเซ็นผู้สมัคร'
export const VALID_CITIZEN_CARD = 'บัตร ปชช ตรงตามทะเบียนราษฎร์'
export const VALID_PAYSLIP = 'สลิปเงินเดือนออกโดยหน่วยงาน'
export const GUARANTOR_SIGNATURE = 'ลายเซ็นผู้คำ'

export const VERIFY_CUSTOMER_DATA = 'ผลการตรวจสอบลูกค้า / ที่ทำงาน'
export const AMOUNT_PRODUCT = 'วงเงิน / ประเภทสินเชื่อที่ขอ'
export const AGE_INCOME_POSITION = 'อายุ / รายได้ / ตำแหน่งงาน'
export const COMPANY_NUMBER = 'เบอร์ที่ทำงาน'
export const AGE_INCOME_POSITION_APPROPRIATE = 'อายุ / รายได้ / ตำแหน่งงานสอดคล้องกันหรือไม่'

export const VERIFY_WITH_BANK = 'ตรวจสอบกับธนาคาร'
export const NAME_ACCOUNT_NUMBER = 'ชื่อลูกค้ากับหมายเลขบัญชี'
export const VALID_STATEMENT = 'ยอดเคลื่อนไหวถูกต้อง'
export const VALID_BALANCE = 'ยอดคงเหลือถูกต้อง'

export const FINANCIAL_HISTORY = 'ประวัติทางการเงิน'
export const IS_EXISTING_CUSTOMER = 'เคยเป็นลูกค้ามาก่อน'
export const HAVE_OTHER_LOAN = 'มีวงเงินกู้กับที่อื่น'
export const TOTAL_ACCOUNT = 'จำนวนบัญชีทั้งหมด'
export const CLOSED_ACCOUNT = 'บัญชีที่ปิดแล้ว'
export const OPEN_ACCOUNT = 'บัญชีที่เปิดอยู่'
export const TOTAL_LOAN = 'ภาระหนี้รวม'
export const TOTAL_MIN_PAY = 'ชำระขั้นต่ำ/เดือน'
export const HAVE_PAST_DUE_STATUS = 'สถานะทางบัญชี'

export const FINANCIAL_STATUS = 'สถานะทางการเงิน'
export const INCOME_MORE_THAN_REQ = 'รายได้สูงกว่าขั้นต่ำ'
export const BALANCE_MORE_THAN_REQ = 'รายได้คงเหลือในบัญชีมากกว่า 4 หลัก'
export const INCOME_MORE_THAN_DEBT = 'รายได้รวมสูงกว่าภาระหนี้รวม มากกว่า 1.3 เท่า'

// Analyse Loan
export const ANALYST_OPINION = 'ความเห็นนักวิเคราะห์'
export const ANALYST_SUGGESTED_AMOUNT = 'วงเงินที่ควรอนุมัติ'
export const APPROVER_OPINION = 'ความเห็นผู้อนุมัติ'
export const APPROVER_AMOUNT = 'วงเงินที่อนุมัติ'
